config/routes.rb
Wardrobe::Application.routes.draw do
  resources :outfits

end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
  attr_accessible :jacket_name, :pants_name, :top_name, :weather 



  def random!
  	shirts = "red,yellow,green,blue,yellow,maroon,black,white,navy".split(',')
  	#shirts = ['red'yellow,green,blue,yellow,maroon,black,white,navy]
  	self.top_name = shirts.sample

  	pants = "jeans,slacks,khakis,slacks,shorts".split(',')
  	self.pants_name = pants.sample

    jackets = "fur,leather,black,sweater".split(',')
    self.jacket_name = jackets.sample
  end

end

    # @@jackets = ["fur", "leather", "brown"]
    # @@pants = ["jeans", "khakis", "slacks"] 
    # @@shirts = ["red", "black", "yellow", "green"]
    # @@weather = (32..120).to_a.sample 

     



    # class Outfit

    # def temp (temp)

    #   puts "Today will be #{@@weather}"
    #   if temp < 60
    #     puts "Cold, a jacket is required"
    #     puts @@jackets.sample()
    #     puts @@shirts.sample()
    #     puts @@pants.sample()
    #     puts "this is  TodaysOutfit"
    #   else
    #     puts "Hot."
    #     puts @@shirts.sample()
    #     puts @@pants.sample()
    #     puts "this is  TodaysOutfit"

    #   end
    # end

    # end

    # today = Outfit.new() 


    # # weather = 59

    # today.temp(@@weather)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  # GET /outfits
  
  def index
    @outfits = Outfit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @outfits }
    end
  end

  # GET /outfits/1
  # GET /outfits/1.json
  def show
    @outfit = Outfit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @outfit }
    end
  end

  # GET /outfits/new
  # GET /outfits/new.json
  def new
    @outfit = Outfit.new

    @outfit.random!

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @outfit }
    end
  end

  # GET /outfits/1/edit
  def edit
    @outfit = Outfit.find(params[:id])
  end

  # POST /outfits
  # POST /outfits.json
  def create
    @outfit = Outfit.new(params[:outfit])

    respond_to do |format|
      if @outfit.save
        format.html { redirect_to @outfit, notice: 'Outfit was successfully created.' }
        format.json { render json: @outfit, status: :created, location: @outfit }
      else
        format.html { render action: "new" }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /outfits/1
  # PUT /outfits/1.json
  def update
    @outfit = Outfit.find(params[:id])

    respond_to do |format|
      if @outfit.update_attributes(params[:outfit])
        format.html { redirect_to @outfit, notice: 'Outfit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outfits/1
  # DELETE /outfits/1.json
  def destroy
    @outfit = Outfit.find(params[:id])
    @outfit.destroy

    respond_to do |format|
      format.html { redirect_to outfits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wardrobe</title>

  <nav>
  	<a href="google.com">Google</a>

  </nav>

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/outfits/_form.html.erb
<%= form_for(@outfit) do |f| %>
  <% if @outfit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outfit.errors.count, "error") %> prohibited this outfit from being saved:</h2>

      <ul>
      <% @outfit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :jacket_name %><br />
    <%= f.text_field :jacket_name %>
  </div>
  <div class="field">
    <%= f.label :top_name %><br />
    <%= f.text_field :top_name %>
  </div>
  <div class="field">
    <%= f.label :pants_name %><br />
    <%= f.text_field :pants_name %>
  </div>
  <div class="field">
    <%= f.label :weather %><br />
    <%= f.text_field :weather %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outfits/edit.html.erb
<h1>Editing outfit</h1>

<%= render 'form' %>

<%= link_to 'Show', @outfit %> |
<%= link_to 'Back', outfits_path %>

app/views/outfits/index.html.erb
<center><h1>Listing outfits</h1></center>

<div class="container"> <!--Boot-->
      <div class="row"> <!--Boot-->
        
        <% @outfits.each do |outfit| %>
        <div class="span3">
          <div class="card">

             <% if outfit.weather == 56 %>
                <h1>Hooolllaa</h1>
                <% else %>
                <h2>Yo</h2>
              <% end %>
            

           <h3> <%= outfit.jacket_name %><br>
            
            <%= outfit.top_name %><br>
            
            <%= outfit.pants_name %><br>

            <%= outfit.weather %><br>
           </h3>    
            

        <div class="btn-group">
          <button class="btn"><%= link_to 'Show', outfit %></button>
          <button class="btn"><%= link_to 'Edit', edit_outfit_path(outfit) %></button>
          <button class="btn"> <%= link_to 'Destroy', outfit, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </div>

            
         </div> <!-- card  -->
          </div>
        <% end %>
      
</div> <!-- The Container -->


          <!-- <ul class="thumbnails">
              <li class="span4">
                <div class="thumbnail">
                  <img data-src="holder.js/300x200" alt="">
                  <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a href="#" class="btn btn-primary">Action</a> <a href="#" class="btn">Action</a></p>
                  </div>
                </div>
              </li>
          </ul> -->
            

<%= link_to 'New Outfit', new_outfit_path %>

app/views/outfits/new.html.erb
<h1>New outfit</h1>

<%= render 'form' %>

<%= link_to 'Back', outfits_path %>

app/views/outfits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Temprature name:</b>
  <%= @outfit.weather %>
</p>


<p>
  <b>Jacket name:</b>
  <%= @outfit.jacket_name %>
</p>

<p>
  <b>Top name:</b>
  <%= @outfit.top_name %>
</p>

<p>
  <b>Pants name:</b>
  <%= @outfit.pants_name %>
</p>




<%= link_to 'Edit', edit_outfit_path(@outfit) %> |
<%= link_to 'Back', outfits_path %>